[package]
name = "PassGen"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
rand = "0.9.2"
arboard = "3.6.0"

[dev-dependencies]
assert_cmd = "2.0.17"
predicates = "3.1.3"

